language: rust
sudo: false
dist: trusty
cache: cargo

rust:
  - nightly
  - beta
  - stable

matrix:
  include:
    - rust: nightly
      before_script:
        - export PATH=$HOME/.cargo/bin:$PATH
        - which cargo-coveralls || cargo install cargo-travis
    - rust: stable
      before_script:
        - export PATH=$HOME/.cargo/bin:$PATH
        - which rustfmt || cargo install rustfmt
      script:
        - eval cargo fmt -- --write-mode=diff
        - eval cargo doc --verbose

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false


addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

script:
  - eval cargo build --verbose $FEATURES
  - eval cargo test --verbose $FEATURES

after_success: |
  case "$TRAVIS_RUST_VERSION" in
    *)
      cargo coveralls --verbose
      ;;
  esac

